// Centralized, client-editable hospital data. Image URLs temporarily reference the current Emergent asset host so the standalone deployment can be launched without an Emergent subscription. Replace with local assets before final production handover.
export const hospital={name:"Sri Aadhya Multi Speciality Hospital",shortName:"Sri Aadhya",tagline:"Multi-Speciality Hospital",motto:"Caring Heart • Healing Hands",location:"Paravada, Andhra Pradesh",address:"Opp. Econoh Hotel, Paravada, Anakapalle District, Andhra Pradesh",phoneDisplay:"+91 90304 81466",phone:"+919030481466",hours:"Open 24 hours"};
export const hospitalLinks={googleMaps:"https://www.google.com/maps/search/?api=1&query=Sri+Aadhya+Multi+Speciality+Hospital+Paravada+Andhra+Pradesh+531021",googleReviews:"https://www.google.com/maps/search/?api=1&query=Sri+Aadhya+Multi+Speciality+Hospital+Paravada+Andhra+Pradesh+531021",justdial:"https://www.justdial.com/Visakhapatnam/Sri-Aadhya-Hospital-Opposite-Econa-Hotel-Paravada/0891PX891-X891-240410125510-F2V3_BZDET",whatsapp:"https://wa.me/919030481466",instagram:"",facebook:"",youtube:"",email:"",phone:"tel:+919030481466",googlePlay:"",appStore:""};
export const mapEmbedUrl="https://maps.google.com/maps?q=Sri%20Aadhya%20Multi%20Speciality%20Hospital%2C%20Paravada%2C%20Andhra%20Pradesh%20531021&t=&z=15&ie=UTF8&iwloc=&output=embed";
export const ratings={google:{rating:"5.0",count:46,label:"Google Reviews"},justdial:{rating:"4.9",count:67,label:"Justdial"}};
export const googleReviews=[{text:"The doctor's service is outstanding, and treatment here helps in quick recovery.",author:"Google review"},{text:"The services were good, and the staff and doctors were excellent in all ways.",author:"Google review"},{text:"Best doctors and affordable healthcare facilities. Thanks to Dr Balakrishna.",author:"Google review"}];
export const justdialReviews=[{text:"My experience at Sri Aadhya Hospital was excellent. The staff was highly attentive, ensuring I felt comfortable throughout my visit.",author:"Mamidi",date:"Oct 2025"},{text:"Sri Aadhya Hospital has excellent staff who are very caring and attentive. They made me feel comfortable and well taken care of during my visit.",author:"Priya Gupta",date:"Jun 2024"},{text:"Sri Aadhya Hospital has excellent facilities and immediate availability. The staff is very attentive and provides great customer service.",author:"Gopi T",date:"Apr 2024"}];
export const departments=[{id:1,icon:"Stethoscope",title:"General Medicine"},{id:2,icon:"Scissors",title:"General Surgery"},{id:3,icon:"HeartHandshake",title:"Obstetrics & Gynaecology"},{id:4,icon:"Baby",title:"Paediatrics"},{id:5,icon:"Bone",title:"Orthopedics"},{id:6,icon:"Sparkles",title:"Dermatology"},{id:7,icon:"HeartPulse",title:"Cardiology"},{id:8,icon:"Activity",title:"Gastroenterology"},{id:9,icon:"Hand",title:"Rheumatology"},{id:10,icon:"Brain",title:"Neurology"},{id:11,icon:"Dna",title:"Endocrinology"},{id:12,icon:"Dumbbell",title:"Physiotherapy"}];
export const facilities=[{id:1,icon:"Stethoscope",title:"OPD & IPD Services"},{id:2,icon:"Siren",title:"24×7 Emergency Care Unit"},{id:3,icon:"Scissors",title:"Advanced Operation Theatre"},{id:4,icon:"Microscope",title:"Laparoscopic Unit"},{id:5,icon:"HeartPulse",title:"Advanced ICU / SICU Care"},{id:6,icon:"Wind",title:"Ventilator"},{id:7,icon:"FlaskConical",title:"Computerised Clinical Laboratory"},{id:8,icon:"ScanLine",title:"Digital X-Ray Unit"},{id:9,icon:"Waves",title:"Ultra Sound"},{id:10,icon:"Radiation",title:"C-Arm"},{id:11,icon:"BedDouble",title:"VIP & Special Patient Rooms"},{id:12,icon:"Pill",title:"24×7 Medical Store"}];
export const insuranceNote="Cashless treatment available through health insurance.";export const aboutStats=["Multi-Speciality Care","24×7 Emergency Care","Patient-Centred Care"];
export const doctors=[{id:1,name:"Dr. B. Bala Krishna",qualification:"M.B.B.S., M.S (Ortho), FIJR"},{id:2,name:"Dr. Amarapu Sravanthi",qualification:"M.D., General Medicine, Dr NB Neurology"},{id:3,name:"Dr. B. Hema Sundar",qualification:"M.B.B.S., M.S General Surgeon"},{id:4,name:"Dr. B. Srikanth",qualification:"M.B.B.S., MD, DM (Cardiology)"},{id:5,name:"Dr. Siva Kumar Burra",qualification:"M.D. General Medicine, Dr NB (Medical Gastroenterology)"},{id:6,name:"Dr. Dharmireddy Venkat",qualification:"M.B.B.S., D.Ch, PGPN, Paediatrics"},{id:7,name:"Dr. Y. Jyothsna",qualification:"M.B.B.S., M.S., Obstetrics & Gynecology"},{id:8,name:"Dr. T. Gopichand",qualification:"M.B.B.S., General Physician"}];
export const serviceGroups=[{group:"Surgeries",items:["Spine Surgery","Arthroplasty","Hand Surgery"]},{group:"Treatments",items:["Neck Pain","Foot Infection"]}];
export const manifesto=[{number:"01",title:"Patient-Focused Care",text:"Every decision begins with what is best for the patient — their comfort, their time and their recovery."},{number:"02",title:"Compassionate Experience",text:"Care delivered with warmth, dignity and respect, for patients and the families who stand beside them."},{number:"03",title:"Clear Communication",text:"Honest guidance and straightforward answers at every step of your visit, in language you understand."},{number:"04",title:"Convenient Access",text:"Located opposite Econoh Hotel, Paravada — and open 24 hours, every day of the year."}];
const BASE="https://aadhya-medical.preview.emergentagent.com/images/hospital/";export const images={logo:BASE+"logo.webp",hero:BASE+"h-02.webp",about:BASE+"h-08.webp"};export const gallery=[{src:BASE+"h-13.webp",alt:"Reception desk at Sri Aadhya Hospital",label:"Reception"},{src:BASE+"h-05.webp",alt:"Patient waiting area with seating",label:"Waiting Area"},{src:BASE+"h-09.webp",alt:"Hospital corridor with enquiry window",label:"Corridor"},{src:BASE+"h-03.webp",alt:"Lobby with lift access",label:"Lobby"},{src:BASE+"h-14.webp",alt:"X-ray room entrance",label:"X-Ray"},{src:BASE+"h-08.webp",alt:"Seating area for patients and attendants",label:"Waiting Lounge"},{src:BASE+"h-01.webp",alt:"Sri Aadhya Hospital signboard on the main road",label:"Signage"},{src:BASE+"h-17.webp",alt:"Hospital building exterior at dusk",label:"Exterior"}];
